Repository ligato/cn-infra, pull requests merged in 2018-08, with the labels that each got.

#323 Generic code cleanup
  Makefile
  datasync/aggregator.go
  datasync/crud.go
  datasync/datasync_api.go
  datasync/events.go
  datasync/grpcsync/plugin_impl_grpsync.go
  datasync/iterator.go
  datasync/kvdbsync/change_event.go
  datasync/kvdbsync/iterator.go
  datasync/kvdbsync/local/global_api.go
  datasync/kvdbsync/local/local_proto_txn.go
  datasync/kvdbsync/options.go
  datasync/kvdbsync/plugin_impl_dbsync.go
  datasync/kvdbsync/watch_impl.go
  datasync/msgsync/options.go
  datasync/msgsync/plugin_impl_msgsync.go
  datasync/resync/plugin_impl_resync.go
  datasync/syncbase/change_event.go
  datasync/syncbase/change_iterator.go
  datasync/syncbase/done.go
  datasync/syncbase/msg/change_event.go
  datasync/syncbase/watcher.go
  db/cryptodata/plugin.go
  db/keyval/bytes_watcher_api.go
  db/keyval/consul/consul.go
  db/keyval/consul/plugin.go
  db/keyval/etcd/bytes_broker_impl.go
  db/keyval/etcd/bytes_txn_impl.go
  db/keyval/etcd/bytes_watcher_impl.go
  db/keyval/etcd/iterator.go
  db/keyval/etcd/plugin_impl_etcd.go
  db/keyval/kvproto/proto_broker_impl.go
  db/keyval/kvproto/proto_watcher_impl.go
  db/keyval/proto_watcher_api.go
  db/keyval/redis/bytes_watcher_impl.go
  db/keyval/redis/plugin_impl_redis.go
  db/sql/sql_watcher_api.go
  logging/logmanager/hooks.go
  logging/logmanager/plugin_impl_log_manager.go
  messaging/kafka/plugin_impl_kafka.go
  rpc/grpc/plugin_impl_grpc.go
  rpc/rest/plugin_impl_rest.go
Labels: 💡 Refactoring

#334 1.5 changelog
  CHANGELOG.md
Labels: 📜 Docs & Examples

#335 Move ListenAndServe for GRPC to AfterInit
  rpc/grpc/plugin_impl_grpc.go
Labels: :bug: Bug
