Repository ligato/cn-infra, pull requests merged in 2018-10, with the labels that each got.

#342 basic rest security using tokens
  .gitignore
  Gopkg.lock
  rpc/rest/README.md
  rpc/rest/config.go
  rpc/rest/http.conf
  rpc/rest/plugin_api_rest.go
  rpc/rest/plugin_impl_rest.go
  rpc/rest/security/auth_store.go
  rpc/rest/security/bindata.go
  rpc/rest/security/model/access-security/accesssecurity.pb.go
  rpc/rest/security/model/access-security/accesssecurity.proto
  rpc/rest/security/password-hasher/README.md
  rpc/rest/security/password-hasher/main.go
  rpc/rest/security/rest_security.go
  rpc/rest/security/templates/login.tmpl
Labels: ⚡️ Feature

#346 Cleanup code generation
  .gitignore
  Gopkg.lock
  Gopkg.toml
  Makefile
  datasync/syncbase/msg/datamsg.pb.go
  examples/etcd-lib/model/phonebook/phonebook.pb.go
  examples/redis-lib/airport/model/flight.pb.go
  health/statuscheck/model/status/status.pb.go
  logging/measure/model/apitrace/apitrace.pb.go
  logging/measure/model/apitrace/apitrace.proto
  vendor/github.com/gogo/protobuf/plugin/compare/compare.go
  vendor/github.com/gogo/protobuf/plugin/compare/comparetest.go
  vendor/github.com/gogo/protobuf/plugin/defaultcheck/defaultcheck.go
  vendor/github.com/gogo/protobuf/plugin/description/description.go
  vendor/github.com/gogo/protobuf/plugin/description/descriptiontest.go
  vendor/github.com/gogo/protobuf/plugin/embedcheck/embedcheck.go
  vendor/github.com/gogo/protobuf/plugin/enumstringer/enumstringer.go
  vendor/github.com/gogo/protobuf/plugin/equal/equal.go
  vendor/github.com/gogo/protobuf/plugin/equal/equaltest.go
  vendor/github.com/gogo/protobuf/plugin/face/face.go
  vendor/github.com/gogo/protobuf/plugin/face/facetest.go
  vendor/github.com/gogo/protobuf/plugin/gostring/gostring.go
  vendor/github.com/gogo/protobuf/plugin/gostring/gostringtest.go
  vendor/github.com/gogo/protobuf/plugin/marshalto/marshalto.go
  vendor/github.com/gogo/protobuf/plugin/oneofcheck/oneofcheck.go
  vendor/github.com/gogo/protobuf/plugin/populate/populate.go
  vendor/github.com/gogo/protobuf/plugin/size/size.go
  vendor/github.com/gogo/protobuf/plugin/size/sizetest.go
  vendor/github.com/gogo/protobuf/plugin/stringer/stringer.go
  vendor/github.com/gogo/protobuf/plugin/stringer/stringertest.go
  vendor/github.com/gogo/protobuf/plugin/testgen/testgen.go
  vendor/github.com/gogo/protobuf/plugin/union/union.go
  vendor/github.com/gogo/protobuf/plugin/union/uniontest.go
  vendor/github.com/gogo/protobuf/plugin/unmarshal/unmarshal.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/Makefile
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/doc.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator/generator.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator/helper.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/generator/internal/remap/remap.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/grpc/grpc.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/main.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/plugin/Makefile
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/plugin/plugin.pb.go
  vendor/github.com/gogo/protobuf/vanity/command/command.go
  vendor/github.com/gogo/protobuf/vanity/enum.go
  vendor/github.com/gogo/protobuf/vanity/field.go
  vendor/github.com/gogo/protobuf/vanity/file.go
  vendor/github.com/gogo/protobuf/vanity/foreach.go
  vendor/github.com/gogo/protobuf/vanity/msg.go
Labels: 💡 Refactoring

#345 Log improvements for agent package
  agent/agent.go
  agent/agent_test.go
  agent/options.go
  agent/plugin_lookup.go
  examples/logs-plugin/main.go
  logging/log_api.go
  logging/measure/tracer.go
Labels: 🔧 Enhancement

#344 cn-infra v1.6 changelog
  CHANGELOG.md
  README.md
  docs/guidelines/CONFIG.md
  docs/guidelines/LOGGING.md
  docs/guidelines/PLUGIN_DEPENDENCIES.md
  docs/guidelines/PLUGIN_FLAVORS.md
  docs/guidelines/PLUGIN_LIFECYCLE.md
  docs/guidelines/README.md
  docs/guidelines/TESTING.md
  examples/simple-agent/README.md
  logging/logmanager/README.md
Labels: 📜 Docs & Examples

#347 Allow to set log verbosity for plugin lookup and plugin start durations
  agent/agent.go
  agent/plugin_lookup.go
  messaging/kafka/plugin_impl_kafka.go
Labels: 🔧 Enhancement

#348 added default resync plugin dependency to etcd options
  CHANGELOG.md
  db/keyval/etcd/options.go
Labels: :bug: Bug

#351 Print stack trace on agent start/stop timeout
  .travis.yml
  agent/agent.go
  agent/options.go
Labels: 🔧 Enhancement

#352 process manager plugin
  processmanager/README.md
  processmanager/options.go
  processmanager/plugin.go
  processmanager/process.go
Labels: ⚡️ Feature
