Repository ligato/cn-infra, pull requests merged in 2018-05, with the labels that each got.

#262 rework grpc plugin
  db/keyval/redis/plugin_impl_redis.go
  flavors/rpc/rpc_flavor.go
  rpc/grpc/config.go
  rpc/grpc/plugin_impl_grpc.go
Labels: enhancement

#263 fixed safeclose error if grpc server is not loaded
  rpc/grpc/plugin_impl_grpc.go
Labels: bug

#264 grpc client support (notification streaming)
  datasync/grpcsync/msgservice.go
  datasync/grpcsync/plugin_impl_grpsync.go
  examples/grpc-plugin/grpc-server/main.go
  rpc/grpc/config.go
  rpc/grpc/listen_and_serve.go
  rpc/grpc/plugin_api_grpc.go
  rpc/grpc/plugin_impl_grpc.go
Labels: feature

#269 in-memory mapping 'update' can trigger events
  idxmap/api.go
  idxmap/mem/inmemory_name_mapping.go
  idxmap/mem/inmemory_name_mapping_test.go
Labels: enhancement

#270 Fix transport for status check
  flavors/connectors/all_connectors_flavor.go
  flavors/connectors/connectors_util.go
Labels: bug

#271 changelog for v1.3
  CHANGELOG.md
Labels: docs

#274 grpc unix domain socket support
  rpc/grpc/config.go
  rpc/grpc/listen_and_serve.go
  rpc/grpc/plugin_impl_grpc.go
Labels: feature

#277 example config files for cn-infra plugins
  CHANGELOG.md
  db/keyval/consul/consul.conf
  db/keyval/etcdv3/etcdv3.conf
  db/sql/cassandra/cassandra.conf
  idxmap/README.md
  logging/logging.conf
  logging/logmanager/plugin_impl_log_manager.go
  messaging/kafka/kafka.conf
  rpc/grpc/config.go
  rpc/grpc/grpc.conf
  rpc/rest/http.conf
Labels: docs

#282 Run all unit tests recursively and fix issues with some tests
  .travis.yml
  Makefile
  db/keyval/etcdv3/mocks/embeded_etcd.go
  health/statuscheck/pluginstatusmap/plugin_status_map.go
Labels: enhancement
