Repository ligato/cn-infra, pull requests merged in 2018-12, with the labels that each got.

#360 refactored redis-lib examples
  examples/redis-lib/airport/airport.go
  examples/redis-lib/simple/simple.go
Labels: 💡 Refactoring, 📜 Docs & Examples

#361 BoltDB watcher
  datasync/events.go
  db/keyval/bolt/bolt.go
  db/keyval/bolt/integration_test.go
  db/keyval/consul/integration_test.go
Labels: ⚡️ feature

#362 update dependencies
  Gopkg.lock
  vendor/github.com/onsi/gomega/.travis.yml
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers/be_closed_matcher.go
  vendor/github.com/onsi/gomega/matchers/be_sent_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_yaml_matcher.go
  vendor/github.com/onsi/gomega/matchers/receive_matcher.go
  vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraph.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/trace.go
  vendor/golang.org/x/net/trace/trace_go16.go
  vendor/golang.org/x/net/trace/trace_go17.go
Labels: 🔗 deps
