Repository ligato/cn-infra, pull requests merged in 2018-07, with the labels that each got.

#308 fix log level setup from config file
  logging/logmanager/README.md
  logging/logmanager/plugin_impl_log_manager.go
Labels: :bug: Bug

#309 Release cn-infra v1.4
  CHANGELOG.md
Labels: 🌟 Release

#311 set defaults to example config files
  db/keyval/consul/consul.conf
  db/keyval/etcd/etcd.conf
  db/sql/cassandra/cassandra.conf
  logging/logging.conf
  messaging/kafka/kafka.conf
  rpc/grpc/grpc.conf
  rpc/rest/http.conf
Labels: 📜 Docs & Examples

#307 allow delayed start for the etcd
  datasync/kvdbsync/plugin_impl_dbsync.go
  db/keyval/consul/plugin.go
  db/keyval/etcd/bytes_broker_impl.go
  db/keyval/etcd/config.go
  db/keyval/etcd/etcd.conf
  db/keyval/etcd/plugin_impl_etcd.go
  db/keyval/plugin_api_keyval.go
  db/keyval/redis/plugin_impl_redis.go
  flavors/connectors/all_connectors_flavor.go
Labels: ⚡️ Feature

#314 Fix trimming prefix for brokers in Consul
  CHANGELOG.md
  db/keyval/consul/consul.go
  db/keyval/consul/consul_integration_test.go
Labels: :bug: Bug

#310 Add cryptodata plugin used to encrypt/decrypt data
  Makefile
  db/cryptodata/client.go
  db/cryptodata/decrypter.go
  db/cryptodata/options.go
  db/cryptodata/plugin.go
  db/cryptodata/wrapper.go
  examples/cryptodata-lib/key-pub.pem
  examples/cryptodata-lib/key.pem
  examples/cryptodata-lib/main.go
  examples/cryptodata-plugin/cryptodata.conf
  examples/cryptodata-plugin/doc.go
  examples/cryptodata-plugin/etcd.conf
  examples/cryptodata-plugin/main.go
Labels: ⚡️ Feature

#318 Implement start/stop timeout for agent
  agent/agent.go
  agent/options.go
Labels: 🔧 Enhancement

#322 Cleanup after refactor
  .gitignore
  Gopkg.lock
  Gopkg.toml
  agent/agent.go
  agent/options.go
  agent/plugin_lookup.go
  config/config_test.go
  config/plugin_config.go
  datasync/kvdbsync/options.go
  datasync/kvdbsync/plugin_impl_dbsync.go
  datasync/msgsync/options.go
  datasync/msgsync/plugin_impl_msgsync.go
  db/cryptodata/options.go
  db/cryptodata/plugin.go
  db/keyval/consul/options.go
  db/keyval/consul/plugin.go
  db/keyval/etcd/options.go
  db/keyval/etcd/plugin_impl_etcd.go
  db/keyval/redis/options.go
  db/keyval/redis/plugin_impl_redis.go
  db/sql/cassandra/options.go
  db/sql/cassandra/plugin_impl_cassa.go
  examples/configs-plugin/main.go
  examples/grpc-plugin/grpc-server/main.go
  health/probe/options.go
  health/probe/plugin_impl_probe.go
  infra/infra.go
  logging/log_api.go
  logging/logmanager/config.go
  logging/logmanager/hooks.go
  logging/logmanager/options.go
  logging/logmanager/plugin_impl_log_manager.go
  logging/logrus/registry.go
  messaging/kafka/options.go
  messaging/kafka/plugin_impl_kafka.go
  rpc/grpc/config.go
  rpc/grpc/listen_and_serve.go
  rpc/grpc/options.go
  rpc/grpc/plugin_impl_grpc.go
  rpc/rest/auth.go
  rpc/rest/config.go
  rpc/rest/listen_and_serve.go
  rpc/rest/options.go
  rpc/rest/plugin_api_rest.go
  rpc/rest/plugin_impl_fork.go
  rpc/rest/plugin_impl_rest.go
  servicelabel/options.go
  servicelabel/plugin_impl_servicelabel.go
Labels: 💡 Refactoring
