Repository ligato/cn-infra, pull requests merged in 2018-09, with the labels that each got.

#336 Fix panic if GRPC is disabled
  rpc/grpc/plugin_impl_grpc.go
Labels: :bug: Bug

#326 KVscheduler
  datasync/syncbase/watcher.go
  idxmap/api.go
  idxmap/mem/inmemory_name_mapping.go
  idxmap/mem/inmemory_name_mapping_test.go
  kvscheduler/api/errors.go
  kvscheduler/api/kv_descriptor_api.go
  kvscheduler/api/kv_scheduler_api.go
  kvscheduler/api/txn_options.go
  kvscheduler/datachange_test.go
  kvscheduler/descriptor/adapter-generator/generator.go
  kvscheduler/descriptor/adapter-generator/template.go
  kvscheduler/descriptor/base/base.go
  kvscheduler/docs/kvscheduler.png
  kvscheduler/docs/migration.png
  kvscheduler/graph/graph_api.go
  kvscheduler/graph/graph_impl.go
  kvscheduler/graph/graph_read.go
  kvscheduler/graph/graph_test.go
  kvscheduler/graph/graph_write.go
  kvscheduler/graph/node_read.go
  kvscheduler/graph/node_write.go
  kvscheduler/graph/utils_for_test.go
  kvscheduler/notification_test.go
  kvscheduler/options.go
  kvscheduler/plugin_scheduler.go
  kvscheduler/refresh.go
  kvscheduler/registry/registry_api.go
  kvscheduler/registry/registry_impl.go
  kvscheduler/registry/registry_test.go
  kvscheduler/rest.go
  kvscheduler/resync_test.go
  kvscheduler/test/arrayval.go
  kvscheduler/test/descriptor.go
  kvscheduler/test/flag.go
  kvscheduler/test/intmeta.go
  kvscheduler/test/southbound.go
  kvscheduler/test/stringval.go
  kvscheduler/txn_exec.go
  kvscheduler/txn_order.go
  kvscheduler/txn_process.go
  kvscheduler/txn_queue.go
  kvscheduler/txn_record.go
  kvscheduler/utils.go
  kvscheduler/utils_for_test.go
  kvscheduler/value/emptyval/emptyval.go
  kvscheduler/value/protoval/protoval.go
  kvscheduler/value_flags.go
Labels: ⚡️ Feature

#339 add state of plugins to liveness probe
  examples/simple-agent/agent.go
  health/statuscheck/model/status/status.pb.go
  health/statuscheck/model/status/status.proto
  health/statuscheck/plugin_impl_statuscheck.go
Labels: 🔧 Enhancement

#340 stopwatch replaced with trace
  logging/measure/README.md
  logging/measure/model/apitrace/apitrace.pb.go
  logging/measure/model/apitrace/apitrace.proto
  logging/measure/stopwatch.go
  logging/measure/tracer.go
Labels: 🔧 Enhancement
