Repository ligato/cn-infra, pull requests merged in 2019-04, with the labels that each got.

#385 move satori/go.uuid to master
  Gopkg.lock
  Gopkg.toml
  logging/logrus/logger.go
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/generator.go
Labels: 🔗 deps

#386 dev -> master
  Gopkg.lock
  Gopkg.toml
  logging/logrus/logger.go
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/generator.go
Labels: 🔗 deps

#388 bolt plugin: rewrite watcher
  db/keyval/bolt/bolt.go
  db/keyval/bolt/broker.go
  db/keyval/bolt/integration_test.go
  db/keyval/bolt/watch.go
Labels: 💡 refactoring

#389 Docs update
  agent/README.md
  agent/agent.go
  agent/doc.go
  infra/infra.go
Labels: 📜 docs & examples
