Repository ligato/cn-infra, pull requests merged in 2019-08, with the labels that each got.

#400 Minor improvements for etcd plugin
  db/keyval/etcd/plugin_impl_etcd.go
Labels: 🔧 enhancement

#401 Process manager: option to set CPU affinity
  exec/processmanager/plugin.go
  exec/processmanager/process_impl.go
  exec/processmanager/process_options.go
  exec/processmanager/template/model/process/process.pb.go
  exec/processmanager/template/model/process/process.proto
  exec/supervisor/config.go
  exec/supervisor/plugin.go
  exec/supervisor/supervisor.conf
Labels: ⚡️ feature

#402 etcd plugin: support CAS and env. variable expansion
  db/keyval/bytes_broker_api.go
  db/keyval/etcd/bytes_broker_impl.go
  db/keyval/etcd/config.go
  db/keyval/etcd/etcd_integration_test.go
  db/keyval/etcd/plugin_impl_etcd.go
  db/keyval/proto_serializer.go
Labels: 🔧 enhancement

#404 prevent possible data race in supervisor stdout/file logger
  exec/supervisor/logger.go
Labels: :bug: bug
