Repository ligato/cn-infra, pull requests merged in 2019-03, with the labels that each got.

#377 changelog draft for new cn-infra release
  CHANGELOG.md
Labels: 🌟 release, 📜 docs & examples

#378 Properly handle config dir paths starting with parent ref ".."
  config/plugin_config.go
Labels: :bug: bug

#381 plugin lookup tutorial
  docs/tutorials/06_plugin-lookup.md
  docs/tutorials/README.md
  examples/tutorials/06_plugin_lookup/main.go
  examples/tutorials/06_plugin_lookup/plugin1.go
  examples/tutorials/06_plugin_lookup/plugin2.go
Labels: 📜 docs & examples

#383 process manager: recover if notify channel is closed from outside
  processmanager/process_impl.go
Labels: :bug: bug
